### ISSUE TITLE
Using FusedLocationProviderClient?

### ISSUE THREAD

**Issue by iadcialim** [yayaa/LocationManager#105]
Question: Are you using FusedLocationProviderClient? Cos FusedLocationProviderApi is already deprecated. Thanks

**Comment by yayaa** [comment]
Thanks for creating this issue.
The library still uses [FusedLocationProviderApi](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderApi) at the moment, and it needs to be updated to [FusedLocationProviderClient](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderClient).
I'll take a look at whenever I can, but any PR is welcome as well 🤗

**Comment by canoondxb** [comment]
Hi

**Comment by canoondxb** [comment]
Hi

**Comment by canoondxb** [comment]
> Question: Are you using FusedLocationProviderClient? Cos FusedLocationProviderApi is already deprecated. Thanks
