### ISSUE TITLE
keepTracking == True does not respect requiredTimeInterval value

### ISSUE THREAD

**Issue by zhombie** [yayaa/LocationManager#112]
...DEFINE YOUR ISSUE...
requiredTimeInterval as written in code documentation `TimeInterval will be used while getting location from default location providers` gives an ability to set location update interval, but LocationManager does not consider this value when keepTracking is True. 

### Configuration

<img width="535" alt="Screenshot 2020-09-26 at 00 13 42" src="https://user-images.githubusercontent.com/26120169/94306850-24238280-ff8d-11ea-9700-ea08b765a3a3.png">

### Logs

<img width="897" alt="Screenshot 2020-09-26 at 00 12 52" src="https://user-images.githubusercontent.com/26120169/94306792-06eeb400-ff8d-11ea-9833-d81cb26701b9.png">

**Comment by yayaa** [comment]
Which version of the library are you using? 
This issue was already raised in !82 and should be solved by [this change](https://github.com/yayaa/LocationManager/commit/4822016fa7d3712b5ee17df24c518974b84a18ba) - could you update the library to the latest version and confirm that issue still exists?

**Comment by zhombie** [comment]
The last version, 2.4.0. I have already seen this issue, but he did not give clear answer about that the change helped him

**Comment by zhombie** [comment]
Tested multiple times, method onLocationChanged() is just firing without any waiting, even the time interval is declared in builder

**Comment by yayaa** [comment]
I have just released the v2.4.1 containing the fix for #116, please give it a try and see that solves the issue you described as well.
