### ISSUE TITLE
Use mock locations

### ISSUE THREAD

**Issue by virgil85** [yayaa/LocationManager#113]
Can I somehow **enable to use mock locations** as well?
I have an external bluetooth GPS receiver which will send with a higher frequency and better accuracy than the internal GPS.
I guess **ALLOW_MOCK_LOCATIONS** in the manifest is one part of the story but how to tell the Location Manager in your library to accept these mocked / test locations?

**Comment by yayaa** [comment]
I am not aware of any need to communicate to allow mock locations - if there is a separate permission, you can add that - but other than that, I don't think there is anything else you need to do.
