### ISSUE TITLE
I want to know about Thread question.

### ISSUE THREAD

**Issue by zhangssdev** [yayaa/LocationManager#119]
This skeleton enjoy me undoubted, It's my honor  to see this plugin!
But i staill have a little question why service of getting location is run in the main thread?
So, i want to know that if service of getting location should or not be in main thread.
help me, please.
i love you.

**Comment by yayaa** [comment]
This is a wrapper library, it does not have any additional thread changes, so it can run in any thread that original location libraries can - mostly and preferably on background thread.
