### ISSUE TITLE
Hiding popups when user enables gps

### ISSUE THREAD

**Issue by tzanou** [yayaa/LocationManager#17]
There is this case where users see the popup to enable gps and they enable it via quick menu,without clicking on the popup.In that case it would be great for the popups to close automatically .

Thanks for the library!

**Comment by yayaa** [comment]
Hey, You are right, thanks for pointing out this.

**Comment by yayaa** [comment]
As far as, i checked there are multiple ways of listening GPS state changes.
 
1- LocationListener, should notify onProviderEnabled or onStatusChanged, but there are cases that doesn't. 
2- GPSStatusChangeListener, deprecated on API 24, but even before that it is also not reliable.
3- GnssStatusCallback, added on API 24, as replacement of GPSStatusChangeListener. But works (or in this case, doesn't work :)) in same way. 

Tried with all of those possible solutions, but not really have an reliable solution. I'll try to look into further if i find more time in future, but feel free to create a PR if you find a solution. @tzanou
