### ISSUE TITLE
Unable to use it with 'com.google.android.gms:play-services-location:8.3.0'

### ISSUE THREAD

**Issue by amankumarjain** [yayaa/LocationManager#2]

**Comment by amankumarjain** [comment]
Is there any way to use without upgrading to 8.4?

**Comment by yayaa** [comment]
You can exclude play-services-location dependency and add it manually which version you want, but since you change the dependency version it may crash any point that i haven't seen in newer version. So test carefully.


   ```
 compile ('com.yayandroid:LocationManager:1.0.4') {
        exclude group: 'com.google.android.gms', module: 'play-services-location'
    }

    compile 'com.google.android.gms:play-services-location:8.3.0'
```
