### ISSUE TITLE
Needs to fail/warn when permissions aren't defined below Android 6.0

### ISSUE THREAD

**Issue by ncapdevi** [yayaa/LocationManager#21]
Had an issue where ACCESS_FINE_LOCATION was enabled, and Android devices above 6.0 were able to ask for permissions and work correctly, but below Android 6.0, it would step in and ask for permissions, but try to use ACCESS_COARSE_LOCATION and silently fail with not feedback from the library.

**Comment by yayaa** [comment]
Did you changed "requiredPermissions" to ask only for ACCESS_FINE_LOCATION? Can you share your configuration please?

And how did you get asked for permissions below 6.0?

**Comment by ncapdevi** [comment]
Configuration
```
        mLocationManager =new LocationManager(new LocationConfiguration()
                .askForSettingsApi(true)
                .askForGooglePlayServices(true)
                .askForEnableGPS(true)
                .setMinAccuracy(500f)
                .setWithinTimePeriod(3*60*1000)
                .setRationalMessage("We need your location")).on(getActivity()).notify(mLocationReceiver);
```

My manifest.xml accidentally only had
`    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
`
and not
`    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
`

So on a device using 5.0, after a `get()` is called,  none of the callbacks occur after.

**Comment by yayaa** [comment]
Ahhh, get your point. 
So below Marshmallow, do the check for required permissions defined in Manifest or not?
Yes, good touch! Thanks, will do it :)

**Comment by ncapdevi** [comment]
Yup! That should take care of it. Thanks for the great work.

**Comment by yayaa** [comment]
I'll keep this open until i actually implement it, so that i'd not just forget it. 
Thanks for pointing out this :)

**Comment by yayaa** [comment]
Hey @ncapdevi 
Can you elaborate the issue a bit more? I cannot reproduce this one.

Because i tried with API Level 22, and when i don't put any of COARSE or FINE locations in manifest, library immediately fails with "Permissions are denied".
