### ISSUE TITLE
Allow distance to be set when keepTracking(true)

### ISSUE THREAD

**Issue by donhill** [yayaa/LocationManager#24]
It looks like a 0 being passed for distance when getting updates. This allows onLocationChange to keep firing even when location.distanceTo(oldLocation) == 0.0F. For now I will calculate the distance but this seems like a lot of radio usage.

The following line is passing in 0 for distance setting

`currentUpdateRequest = new UpdateRequest(provider, timeInterval, 0, locationChangeListener);`

[https://developer.android.com/reference/android/location/LocationManager.html#requestLocationUpdates(java.lang.String, long, float, android.location.LocationListener)](url)

**Comment by yayaa** [comment]
You're right! I should update this :) Will be done, within current developments and announce here.
Thanks for reporting 👍

**Comment by yayaa** [comment]
v2.0.0 is just released, and it is possible now.

**Comment by donhill** [comment]
Great thanks for the update.
