### ISSUE TITLE
Rationale dialog content is always collapsed!

### ISSUE THREAD

**Issue by khaledkhj** [yayaa/LocationManager#25]
Any way to expand the content of the rationale dialog?
I remember it was showing all the content previously, but now it is not!

![untitled](https://cloud.githubusercontent.com/assets/2294141/22819640/0001f5b4-efae-11e6-8173-ec55b7d8d034.png)

Thank you.

**Comment by yayaa** [comment]
Never saw this actually, can be a new introduced feature? I'll take a look, maybe the method's itself is also updated then yes, otherwise i'm not sure :)

**Comment by yayaa** [comment]
Wait, this is just an AlertDialog
https://github.com/yayaa/LocationManager/blob/master/library/src/main/java/com/yayandroid/locationmanager/helper/PermissionManager.java#L79
Can you give me more information about how do you get this view? On which device and OS version, please?

**Comment by khaledkhj** [comment]
Yes sure.
I am just running the sample that you provide with the library, and getting that dialog with collapsed information!

I tested it on Samsung devices, Galaxy Tab A and S4.

**Comment by yayaa** [comment]
This is really very specific case, and i don't believe this is nothing this library should maintain. Issue might even be related that Samsung devices display customized version of AlertDialog. 

Again, it is default AlertDialog usage. Maybe i can try to extract displaying AlertDialog or at least provide a solution to switch dialog creation.

**Comment by yayaa** [comment]
v2.0.0 is just released, and it is possible to create your own dialog implementation.

**Comment by khaledkhj** [comment]
That is a great news.
Thank you.
