### ISSUE TITLE
method useOnlyGPService not acting right behavior as document says

### ISSUE THREAD

**Issue by xxxifan** [yayaa/LocationManager#30]
useOnlyGPService documentation:

```
While this is set true default location providers (GPS & Network)
 will not be used to receive location, set false if you want them to be used.
```

but actually it been using for check whether to use GooglePlay service instead of GPS service
https://github.com/yayaa/LocationManager/blob/master/library/src/main/java/com/yayandroid/locationmanager/LocationManager.java#L249

and there's another method for decide whether to use GooglePlay service ```doNotUseGooglePlayServices```

**Comment by yayaa** [comment]
Naming issue :( GPService = GooglePlayService not GPS 
It'll be fixed with v2 still working on it though :)

**Comment by xxxifan** [comment]
But I need a function like the doc says :( please

**Comment by yayaa** [comment]
So you don't want to use GooglePlayServices or/and Network Provider? But only GPS provider?

**Comment by xxxifan** [comment]
yes, can you make it :P

**Comment by yayaa** [comment]
I'll consider within v2 :) But you can always set your own LocationProvider? Just extend LocationProvider class do your GPS Provider implementation and should be fine

**Comment by yayaa** [comment]
And one more thing, if library is able to retrieve location in given waiting period for GPS then it'll not switch to network. So you can set `setWaitPeriod` for GPS long enough you think that you'd receive location from, and network will never be used. And for the GooglePlayServices you can set `doNotUseGooglePlayServices`

So it is already possible.

**Comment by xxxifan** [comment]
Thanks for the tip, I was doing like this and works like a charm, thanks ;)

**Comment by yayaa** [comment]
You're welcome :)
