### ISSUE TITLE
duplicate entry error after adding firebase dependencies

### ISSUE THREAD

**Issue by mahermeg17** [yayaa/LocationManager#32]
Hi,

All work fine until I add some firebase dependencies
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/common/api/zzd.class

even I add to my build file : 
`
packagingOptions {

        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
    }
    dexOptions {
        jumboMode true
        javaMaxHeapSize "4g"
    }`

**Comment by yayaa** [comment]
Can you try to `exclude group: 'com.google.android.gms'` from firebase?

**Comment by yayaa** [comment]
Any feedback on this? @mahermeg17
