### ISSUE TITLE
How disable Google Play and use only wifi and GPS?

### ISSUE THREAD

**Issue by no-cat-no** [yayaa/LocationManager#38]
I'm making an app for China. But in China, Google Play Services do not work (Great Firewall). Tell me, how can I turn off location determination through Google Play Services and leave only GPS and WiFi?

Thanks!

P.S. Do you planing to add a definition through the GSM of the towers?

**Comment by kobasek** [comment]
> Tell me, how can I turn off location determination through Google Play Services and leave only GPS and WiFi?

Configurations.java

```
public static LocationConfiguration defaultConfiguration(@NonNull String rationalMessage, @NonNull String gpsMessage) {
        return new LocationConfiguration.Builder()
              .askForPermission(new PermissionConfiguration.Builder().rationaleMessage(rationalMessage).build())
              .useGooglePlayServices(new GooglePlayServicesConfiguration.Builder().build())
              .useDefaultProviders(new DefaultProviderConfiguration.Builder().gpsMessage(gpsMessage).build())
              .build();
    }
```
Just delete this line:
` .useGooglePlayServices(new GooglePlayServicesConfiguration.Builder().build())`
and you're ready to go.

> P.S. Do you planing to add a definition through the GSM of the towers?

DefaultLocationProvider.java

```
void getLocationByNetwork() {
        if (isNetworkProviderEnabled() && getSourceProvider().isNetworkAvailable(getContext())) {
            LogUtils.logI("Network is enabled, getting location...");
            askForLocation(LocationManager.NETWORK_PROVIDER);
        } else {
            LogUtils.logI("Network is not enabled, calling fail...");
            onLocationFailed(FailType.NETWORK_NOT_AVAILABLE);
        }
    }
```
If  you change the conditions and keep only `isNetworkProviderEnabled()`, network provider will be used whether there is an available active data network or not.

**Comment by no-cat-no** [comment]
Wow! Thanks!!!

**Comment by no-cat-no** [comment]
And small question:

If you do not use Google Services, the battery will be installed faster. For tracking this is critical. Could you give advice on how to reduce battery consumption? Can I use services instead of activating or something like that?

I noticed that you are not using PASSIVE_PROVIDER.

**Comment by kobasek** [comment]
The Google Location Services API provides, in most cases, better battery performance. 

> Could you give advice on how to reduce battery consumption?

[https://developer.android.com/guide/topics/location/strategies.html#Adjusting](url)

> I noticed that you are not using PASSIVE_PROVIDER.

[https://developer.android.com/reference/android/location/LocationManager.html#PASSIVE_PROVIDER](url)

[http://stackoverflow.com/questions/5655241/what-is-the-meaning-of-android-location-locationmanager-passive-provider#answer-5655329](url)

**Comment by no-cat-no** [comment]
ok, thanks.

**Comment by yayaa** [comment]
wow @kobasek thanks for answering :) Appreciated!

Actually removing network availability check is good idea, eventually we have timeout anyway. I'll implement it that way, hopefully soon :)

**Comment by yayaa** [comment]
And @no-cat-no if you need to customize the behaviour even further, you can create your own LocationProvider implementation and set it to LocationManager. Then, it will not use default ones, and since you're not using GooglePlayServices api provider anyway, that would mean for your case, only DefaultLocationProvider changes.

In that way, you can do any optimisation that you need to do, such as: using PassiveProvider.

**Comment by kobasek** [comment]
I've done some minor/major "fixes" to your project @yayaa  If i have more time, i'll create a PR and share all of it with you.

**Comment by yayaa** [comment]
Nice 👍 Just a few notes:
- Please create separate PRs if the things are not related, instead of having one PR with all changes. So that, even some parts need to be changed, i can still accept the others. 
- Descriptive commit names are required.
- Would be also nice if you split the PR that you have already [here](https://github.com/yayaa/LocationManager/pull/37)

**Comment by kobasek** [comment]
Sure ;)
Have you considered wrapping your library with RxJava?

**Comment by yayaa** [comment]
I did, but because there are already some with RxJava i decided not to, but sure why not. I would do in a different module though, just not force people to depend RxJava if they are not already using. But please send me email if you are interested, let's not talk over a closed issue :) @kobasek
