### ISSUE TITLE
Good library, please add support to work in Service

### ISSUE THREAD

**Issue by leshka890** [yayaa/LocationManager#5]

**Comment by nurgasemetey** [comment]
+1

**Comment by yayaa** [comment]
I'll implement it, as soon as i get free time :) 
You are welcome to send a pull request though.

**Comment by orhanturk** [comment]
Teşekkürler güzel bir kütüphane olmuş

**Comment by zoontek** [comment]
No news on this?

**Comment by yayaa** [comment]
Currently i'm too busy, but i really want to implement it sometimes. Just not know when it will be possible for me... Sorry guys for delay. But again, if there is any volunteer i'll gladly accept the pull requests :)

**Comment by zoontek** [comment]
I would love to make a PR, but I don't know much about Android... I currently try to create a React Native bridge for it :)

**Comment by yayaa** [comment]
Nice! That'd be the second thing on my mind :) Looking forward to receive a PR @zoontek :) Hit me up if you have any question in the process though.

**Comment by IvoPereira** [comment]
I'm looking for this too.

**Comment by RishiSangal** [comment]
Hey i am trying to implement it on the service so lets hope i gets successful.

**Comment by yayaa** [comment]
Hey @RishiSangal ,
I'm working on v2.0 big changes coming up :) it will also have service support. I cannot give a deadline tho, still there are stuff to do :) Either you can choose to wait or try to implement your way out. Just wanted to let you know that it is already on it's way!

**Comment by RishiSangal** [comment]
Hi 

I have implemented it in service but there is another issue like if the Location is off its unable to fetch the location from Network or Wifi have you faced the same issue .

**Comment by yayaa** [comment]
@RishiSangal try to extend waiting period for Network, and ensure your wifi is on. Network Provider is the least reliable one -as in returning location- that's why it is the last option :)

**Comment by yayaa** [comment]
v2.0.0 is just released, and it is possible to use within a service now.
