### ISSUE TITLE
Stop location updates

### ISSUE THREAD

**Issue by marktonni** [yayaa/LocationManager#51]
Hi,

Once the service is started and getlocation() is called, how do you stop getting location updates? I can stop the service but I'm still getting the location updates, this is in your sample project. I`m using keepTracking(true) and this config.

LocationConfiguration awesomeConfiguration = new LocationConfiguration.Builder()
                .keepTracking(true)
                .useDefaultProviders(new DefaultProviderConfiguration.Builder()
                        .requiredTimeInterval(3 * 1000)
                        .acceptableAccuracy(10.0f)
                        .setWaitPeriod(ProviderType.GPS, 30 * 1000)
                        .build())
                .build();

thank you in advance.

**Comment by yayaa** [comment]
You can call, `cancel` method on `LocationManager` object.
