### ISSUE TITLE
A BaseLocationListener class would be nice

### ISSUE THREAD

**Issue by ridcully99** [yayaa/LocationManager#53]
It would be nice to have a BaseLocationListener class with empty implementations of LocationListener.

It would make code cleaner when we only want to implement 1 oder 2 methods of the LocationListener interface.

We could then write

    .notify(new BaseLocationListener() {
        public void onLocationChanged(Location location) {
            // do something with location.
        }
    })

**Comment by yayaa** [comment]
Actually i implemented such thing, but then removed it :) 
I guess i should re-place it 👍

**Comment by ridcully99** [comment]
That would be nice :-)

**Comment by yayaa** [comment]
It's there, releasing 2.0.3 should be available soon, enjoy! :) https://github.com/yayaa/LocationManager/pull/54
