### ISSUE TITLE
Main UI thread is stuck until it will update location view from callback 

### ISSUE THREAD

**Issue by credisheelu** [yayaa/LocationManager#61]
...DEFINE YOUR ISSUE...

### Configuration
```java
PLEASE SHARE YOUR CONFIGURATION OBJECT HERE
```

### Logs
PLEASE SHARE YOUR LOGS

**Comment by yayaa** [comment]
Please update the issue according to template

**Comment by credisheelu** [comment]
When i was update texview in onLocationChanged callback in activity, the screen was hanged until and unless the textview is updated

**Comment by yayaa** [comment]
Ok, let's try again; Please update the issue according to template. Share required information on description, and some code how did you implement so that i can help you. Otherwise i'll close the issue.
