### ISSUE TITLE
Please update the latest dependency version from x.y.z to 2.3.0

### ISSUE THREAD

**Issue by credisheelu** [yayaa/LocationManager#62]
...DEFINE YOUR ISSUE...

### Configuration
```java
PLEASE SHARE YOUR CONFIGURATION OBJECT HERE
```

### Logs
PLEASE SHARE YOUR LOGS

**Comment by yayaa** [comment]
x.y.z is placeholder, you should replace that with version by yourself. And latest released version is 2.0.3

**Comment by waqaruet** [comment]
add somewhere in info where we can see what the lattest version... lame you closed this issue without fixing it. I am still facing this issue in 2019! time to leave the earth

**Comment by yayaa** [comment]
For any open source project in Github, you can (hopefully) find the latest release in releases page
https://github.com/yayaa/LocationManager/releases
