### ISSUE TITLE
FragmentActivity

### ISSUE THREAD

**Issue by kkrishnan90** [yayaa/LocationManager#7]
Thanks for such an amazing library. 
Now, I would like to know how can I use your library in a class which already extends FragmentActivity. 
I actually have a tab with viewpager architecture in which one of the tab receives location updates continuously and moves the marker on the map .. 
Thanks in advance

**Comment by yayaa** [comment]
You need to create a locationManager instance by yourself, but ensure to notify it on every required step of your Activity. See [LocationBaseActivity](https://github.com/yayaa/LocationManager/blob/master/Library/app/src/main/java/com/yayandroid/locationmanager/LocationBaseActivity.java)

Then i would suggest you to trace location in the activity, then push it into your fragment when received.

**Comment by rajeevjaiswal** [comment]
@yayaa I need to trigger getlocation method from a fragment. So I extended LocationBaseActivity to the parentActivity of the fragment and implemented the methods.
I am calling getLocation methodof the activity from the fragment Which works and I get the location.
But how do I pass this location to my current fragment? Otherthan using sharedpreference

**Comment by yayaa** [comment]
You can use [findFragmentByTag](https://developer.android.com/reference/android/app/FragmentManager.html#findFragmentByTag(java.lang.String)) to get your fragment's instance and have a public method on it to pass location, or you can set a localBroadcastReceiver to listen a specific action and send that broadcast when you receive location updates, or create a static location field in any class and set / get to that value from anywhere or so on... There are lots of options, pick the one suits you better.
