### ISSUE TITLE
ContinuousTask delayed null exception

### ISSUE THREAD

**Issue by pmsferreira** [yayaa/LocationManager#74]
Sometimes when I call getLocation(), I get this exception "**Attempt to invoke virtual method 'void com.yayandroid.locationmanager.helper.continuoustask.ContinuousTask.delayed(long)' on a null object reference**". 

### Configuration

    private static final int WAIT_PERIOD = 1000;

    public static LocationConfiguration getConfiguration(){

        LocationRequest locationRequest = LocationRequest.create()
                .setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY);
        
        //google play services configuration
        GooglePlayServicesConfiguration gpsc = new GooglePlayServicesConfiguration.Builder()
                .locationRequest(locationRequest)
                .askForGooglePlayServices(true)
                .askForSettingsApi(true)
                .ignoreLastKnowLocation(true)
                .setWaitPeriod(WAIT_PERIOD)
                .build();

        //location configuration
        LocationConfiguration.Builder locationConfiguration = new LocationConfiguration.Builder();
        locationConfiguration
                .keepTracking(false)
                .useGooglePlayServices(gpsc)
                .askForPermission(new PermissionConfiguration.Builder().build())
                .useDefaultProviders(new DefaultProviderConfiguration.Builder()
                        .setWaitPeriod(ProviderType.DEFAULT_PROVIDERS, WAIT_PERIOD)
                        .build());

        return locationConfiguration.build();
    }

### Logs
LocationManager: We got permission!
DispatcherLocationProvider: GooglePlayServices is available on device.
DispatcherLocationProvider: Attempting to get location from Google Play Services providers...
: Attempt to invoke virtual method 'void com.yayandroid.locationmanager.helper.continuoustask.ContinuousTask.delayed(long)' on a null object reference

**Comment by yayaa** [comment]
Thanks for reporting, are you able to reproduce this issue in a particular pattern / usecase? Or It happens randomly?

**Comment by pmsferreira** [comment]
Hi @yayaa it only happens randomly when i use getLocation() inside a thread runnable:

final Handler handler = new Handler();
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                if(location  != null ) { /* app code */ }
                        });
                    }
                }
                else
                    handler.postDelayed(this, 500);
            }
        };
        handler.post(runnable);
        getLocation();

**Comment by stoefln** [comment]
Same here!

**Comment by yayaa** [comment]
Sorry for late action, but [this](https://github.com/yayaa/LocationManager/commit/9875e7b24929c391be151f94d02ca7bc998aa397) should solve the problem. 

I'll try to do other bugfixes as well, and release 2.1.0 version as short term plan.
