### ISSUE TITLE
Cant compile

### ISSUE THREAD

**Issue by farzadi** [yayaa/LocationManager#75]
When I want to compile LoactionManager I get error 

Error:(41, 13) Failed to resolve: com.yayandroid:LocationManager:x.y.z

**Comment by mabdelaal86** [comment]
Please use the library version, for example (1.1.3), instead of x.y.z
So your build.gradle file will looks like:

```
dependencies {
     compile 'com.yayandroid:LocationManager:1.1.3'
}
```

Please review this page for more details:
[Location Manager](https://devhub.io/zh/repos/yayaa-LocationManager)
