### ISSUE TITLE
Persisting across configuration changes?

### ISSUE THREAD

**Issue by rmtheis** [yayaa/LocationManager#76]
Have you considered adjusting this library so that it persists across configuration changes or is lifecycle-aware?

https://developer.android.com/topic/libraries/architecture/lifecycle.html

**Comment by yayaa** [comment]
You are right, it should persist 🤔

**Comment by yayaa** [comment]
By the way, library is already lifecycle aware as long as you called required methods :) I might consider in future to adapt with Architecture components though 👍

**Comment by yayaa** [comment]
Considering that library should already persist, I do not consider using arch components as external dependency. I'll close this issue, feel free to re-open if you have any further question or request about it.
