### ISSUE TITLE
Power saving by Stop tracking if phone not moving for x time using accelerometer & Gyrometer

### ISSUE THREAD

**Issue by waleedmakarem** [yayaa/LocationManager#78]
First , thanks for this great library, and great explanation as well

I think it will be great addition if you could improve power consumption by Stopping tracking if phone not moving for x time using accelerometer & Gyrometer.
Thanks again..

**Comment by yayaa** [comment]
Thank you for the feedback :)
About the stopping tracking, I see that as an implementation detail and I would rather not to introduce more complexity to the library.

**Comment by waleedmakarem** [comment]
Thanks for feedback, and the library :)
