### ISSUE TITLE
Marshmallow Timeout

### ISSUE THREAD

**Issue by Betobit** [yayaa/LocationManager#8]
Hi, awesome library I like the clean code but I have a problem with Marshmallow devices. I just can't make it work, always throws failType = 5.

I have all the permission in the manifest.

Thanks.

**Comment by yayaa** [comment]
Thanks for your kind comment :)

First of all, FailType.TIME_OUT doesn't mean that you have anything wrong, but it means it wasn't possible to receive location update in specified time periods. What is your configurations? You may try with higher provider wait time periods...

**Comment by Betobit** [comment]
Thanks for the fast answer. Here is my LocationConfiguration()

```
  return new LocationConfiguration()
                .keepTracking(false)
                .askForGooglePlayServices(true)
                .setMinAccuracy(200.0f)
                .setWaitPeriod(ProviderType.GOOGLE_PLAY_SERVICES, 5 * 1000)
                .setWaitPeriod(ProviderType.GPS, 10 * 1000)
                .setWaitPeriod(ProviderType.NETWORK, 5 * 1000)
                .setGPSMessage("Would you mind to turn GPS on?")
                .setRationalMessage("Gimme the permission!");
```

The problem only happen with > API 23

**Comment by yayaa** [comment]
Are you using emulator/genymotion to test on Android API 23? If so, please try with real device as well.

**Comment by Betobit** [comment]
Ok, I will try on a real device ;)

**Comment by Betobit** [comment]
Thank you @yayaa. I wasn't sending the location to my emulator. jeje

**Comment by yayaa** [comment]
Glad to help :)
