### ISSUE TITLE
requiredTimeInterval not being considered when keepTracking is enabled

### ISSUE THREAD

**Issue by Fuhrmann** [yayaa/LocationManager#82]
I'm using a Service to get the user location and keep track of it. This is my configuration:

```java
override fun getLocationConfiguration(): LocationConfiguration {
    return LocationConfiguration.Builder()
            .useDefaultProviders(DefaultProviderConfiguration.Builder()
                    .acceptableAccuracy(10.0f)
                    .requiredTimeInterval(5 * 60 * 1000) // 5 minutes
                    .acceptableTimePeriod(5 * 60 * 1000) // 5 minutes
                    .setWaitPeriod(ProviderType.GPS, 20 * 1000) // 20 seconds
                    .setWaitPeriod(ProviderType.NETWORK, 20 * 1000) // 20 seconds
                    .gpsMessage("Turn GPS on?")
                    .build())
            .keepTracking(true)
            .build()
}
```

My `onLocationChange` method:

```
override fun onLocationChanged(location: Location) {
    MyAsyncTask(location.latitude, location.longitude).execute()
}
```

Then in MyAsyncTask I just send the data to my server.

I start the service in my MainActivity:

```
startService(Intent(this, MyService::class.java))
```

I specify that I want the location every 5 minutes and want to keep track of it. I setup the emulator GPS data with a KML file and start the emulator GPS playback:

![image](https://user-images.githubusercontent.com/1160365/39462007-7718911c-4cdc-11e8-9252-46d36b17d168.png)

As you can see in the image above the data have a delay of 2 seconds between every location update. Even with the 2 seconds delay on each update, I dont want to be notified every 2 seconds. I want to be notified in a interval of 5 minutes as I specified in the configuration builder. Is this possible? Am I missing something, maybe this is supposed to work this way?

### Logs
```
5-01 01:06:45.546 10114-10146/? D/MyService$MyAsyncTask: Sending location to server
05-01 01:06:47.565 10114-10150/? D/MyService$MyAsyncTask: Sending location to server
05-01 01:06:49.609 10114-10146/? D/MyService$MyAsyncTask: Sending location to server
05-01 01:06:51.607 10114-10150/? D/MyService$MyAsyncTask: Sending location to server
05-01 01:06:53.652 10114-10146/? D/MyService$MyAsyncTask: Sending location to server
05-01 01:06:55.713 10114-10150/? D/MyService$MyAsyncTask: Sending location to server
05-01 01:06:57.704 10114-10146/? D/MyService$MyAsyncTask: Sending location to server
05-01 01:06:59.734 10114-10150/? D/MyService$MyAsyncTask: Sending location to server
05-01 01:07:01.739 10114-10146/? D/MyService$MyAsyncTask: Sending location to server
05-01 01:07:03.807 10114-10150/? D/MyService$MyAsyncTask: Sending location to server
05-01 01:07:05.832 10114-10146/? D/MyService$MyAsyncTask: Sending location to server
05-01 01:07:07.847 10114-10150/? D/MyService$MyAsyncTask: Sending location to server
05-01 01:07:09.895 10114-10146/? D/MyService$MyAsyncTask: Sending location to server
05-01 01:07:11.911 10114-10150/? D/MyService$MyAsyncTask: Sending location to server
05-01 01:07:13.968 10114-10146/? D/MyService$MyAsyncTask: Sending location to server
05-01 01:07:15.995 10114-10150/? D/MyService$MyAsyncTask: Sending location to server
05-01 01:07:17.981 10114-10146/? D/MyService$MyAsyncTask: Sending location to server
05-01 01:07:19.999 10114-10150/? D/MyService$MyAsyncTask: Sending location to server
```

Thank you for your help!

**Comment by yayaa** [comment]
Good catch! 👍 
I assume it happens because, everytime I [request](https://github.com/yayaa/LocationManager/blob/463e10412266a5b76360e34a27b5741508e00afc/library/src/main/java/com/yayandroid/locationmanager/helper/UpdateRequest.java#L34) a new update but don't cancel the previous one. Which initially it requests immediate update as timeInterval 0.

**Comment by Fuhrmann** [comment]
Nice! I'm using the AlarmManager instead for now! It works great.

**Comment by yayaa** [comment]
Sorry for late action, but [this](https://github.com/yayaa/LocationManager/commit/4822016fa7d3712b5ee17df24c518974b84a18ba) should solve the problem.

I'll try to do other bugfixes as well, and release 2.1.0 version as short term plan.

**Comment by Fuhrmann** [comment]
No problem, thanks for taking the time to fix this issue!
