### ISSUE TITLE
I got error like uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by shubhamkhuva** [yayaa/LocationManager#83]
/source_project/locationlib/src/main/java/com/yayandroid/locationmanager/providers/locationprovider/GooglePlayServicesLocationSource.java:
uses or overrides a deprecated API.
Recompile with -Xlint:deprecation for details.

with this error
A failure occurred while executing com.android.build.gradle.internal.transforms.JacocoTransform$JacocoWorkerAction

project Gradle
 implementation 'com.google.firebase:firebase-messaging:15.0.0'
    implementation 'com.google.firebase:firebase-auth:15.0.0'
    implementation 'com.google.firebase:firebase-core:15.0.0'

LocationLib
implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.google.android.gms:play-services:12.0.1'
    implementation 'com.google.android.gms:play-services-maps:9.0.1'
    implementation 'com.google.android.gms:play-services-location:9.0.1'

**Comment by yayaa** [comment]
Just released v2.2.0 with all dependencies updated - please give it a try, that should solve this issue.
