### ISSUE TITLE
Fatal Exception (NullPointerException) - ContinuousTask.stop() on a null object reference

### ISSUE THREAD

**Issue by kibrushi** [yayaa/LocationManager#92]
First of all thank you very much for this library.
When i look in fabc.io i'm always having this error. It's something i do wrong or it's library bug? 
Thank you in advance
### Configuration
```java
- java 8
- minSdkVersion : 23
- targetSdkVersion : 27
- lib : com.yayandroid:LocationManager:2.0.4

```

### Logs

com.yayandroid.locationmanager.providers.locationprovider.DefaultLocationProvider.onLocationChanged (Unknown Source)
--
  | android.location.LocationManager$ListenerTransport._handleMessage (LocationManager.java:285)
  | android.location.LocationManager$ListenerTransport.access$000 (LocationManager.java:214)
  | android.location.LocationManager$ListenerTransport$1.handleMessage (LocationManager.java:230)
  | android.os.Handler.dispatchMessage (Handler.java:102)
  | android.os.Looper.loop (Looper.java:154)
  | android.app.ActivityThread.main (ActivityThread.java:5527)
  | java.lang.reflect.Method.invoke (Method.java)
  | com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:739)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:629)

**Comment by yayaa** [comment]
Sorry for late action, but [this](https://github.com/yayaa/LocationManager/commit/ee2d64c5fe5ded305268528c18c3d2645118e52e) should solve the problem.

I'll try to do other bugfixes as well, and release 2.1.0 version as short term plan.
