### ISSUE TITLE
Which version should i use ? 

### ISSUE THREAD

**Issue by Dhruvjain2000** [yayaa/LocationManager#94]
...DEFINE YOUR ISSUE...

### Configuration
```java
PLEASE SHARE YOUR CONFIGURATION OBJECT HERE
```
It's throwing class not found exception at getLocation() method
### Logs
PLEASE SHARE YOUR LOGS

Caused by: java.lang.ClassNotFoundException: Didn't find class 

"com.google.android.gms.common.api.Api$zzf" on path: DexPathList[[zip file "/data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/base.apk", zip file "/data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_resources_apk.apk", zip file "/data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/lib/arm64, /data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/base.apk!/lib/arm64-v8a, /data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.example.android.teamtracker-xRvCp-kK1G8jXa1ajYLtBw==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by yayaa** [comment]
From Title, I assume you were not able to find the latest released version of the library which is 2.0.4 and you can see it on [releases tab on Github](https://github.com/yayaa/LocationManager/releases).

The log output you gave shows you have multidex issue.

Could you please clarify the question if this does not already answer?
